name = 'Simple Portfolio'
license = 'MIT'
# licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'A simple theme for an advertising portfolio'

# The home page of the theme, where the source can be found
# homepage = 'https://github.com/owner/repo'

# If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['personal', 'portfolio']
features = ['minimal', 'responsive', 'bootstrap']

# If the theme has a single author
[author]
  name = 'Harvey Lieberman'
  homepage = 'https://www.harveyl888.com'
